"""third Migration

Revision ID: 147072af6171
Revises: 373b894f2e3b
Create Date: 2022-05-16 10:57:18.593099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '147072af6171'
down_revision = '373b894f2e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_index('ix_pitches_posted', table_name='pitches')
    op.create_index(op.f('ix_pitches_timestamp'), 'pitches', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'pitches', 'users', ['user_id'], ['id'])
    op.drop_column('pitches', 'posted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_index(op.f('ix_pitches_timestamp'), table_name='pitches')
    op.create_index('ix_pitches_posted', 'pitches', ['posted'], unique=False)
    op.drop_column('pitches', 'timestamp')
    op.drop_column('pitches', 'user_id')
    # ### end Alembic commands ###
