"""second Migration

Revision ID: 373b894f2e3b
Revises: 211dac55851a
Create Date: 2022-05-16 08:36:45.376724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373b894f2e3b'
down_revision = '211dac55851a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downvotes_timestamp'), 'downvotes', ['timestamp'], unique=False)
    op.create_table('upvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upvotes_timestamp'), 'upvotes', ['timestamp'], unique=False)
    op.create_unique_constraint(None, 'categories', ['category_name'])
    op.create_index(op.f('ix_comments_posted'), 'comments', ['posted'], unique=False)
    op.create_index(op.f('ix_pitches_posted'), 'pitches', ['posted'], unique=False)
    op.drop_constraint('pitches_pitcher_id_fkey', 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'upvotes')
    op.drop_column('pitches', 'downvotes')
    op.drop_column('pitches', 'pitcher_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitcher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('downvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitches_pitcher_id_fkey', 'pitches', 'users', ['pitcher_id'], ['id'])
    op.drop_index(op.f('ix_pitches_posted'), table_name='pitches')
    op.drop_index(op.f('ix_comments_posted'), table_name='comments')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_index(op.f('ix_upvotes_timestamp'), table_name='upvotes')
    op.drop_table('upvotes')
    op.drop_index(op.f('ix_downvotes_timestamp'), table_name='downvotes')
    op.drop_table('downvotes')
    # ### end Alembic commands ###
